% Math 151A, Project 2 sample code

function st = evalS(S,t_int,t_test)
%evaluates the spline with coefficients S through points t_int
%at a set of points t_test. See spline3 for the format of S.
% 
% Input:
%   S - The spline coefficients, generated by spline3
%   t_int - The interpolating points used for S
%   t_test - The sample points to be evaluated
% 
% Output:
%   st - the interpolant evaluated at t_test

nX = length(t_int);
nXs = length(t_test);
st(1:nXs,1) = 0;
for i=1:nXs
   x = t_test(i);
   
   %Ensure that the test point lies in the interval
   % (no extrapolation allowed)
   if(x>t_int(end) || x<t_int(1))
       fprintf('Not in the interval!\n');
       st = t_int;
       return;
   end
   
   j = find(x >= t_int,1,'last'); % use j-th spline
   if(j>=nX) %fix if x is the right endpoint
      j = nX-1; 
   end
   
   %st(i) = S(j,1) + S(j,2)*dx + S(j,3)*dx^2 + S(j,4)*dx^3;
   dx = x-t_int(j);
   tmp = S(j,3) + S(j,4)*dx;
   tmp = S(j,2) + tmp*dx;
   st(i) = S(j,1) + tmp*dx;
end