% Math 151A, Project 2 sample code

function pt=evalP(P,t_int,t_test)
% Evaluates the Lagrange interpolant P_n through points t_int
% at a set of points t_test. The vector P contains the coefficients
% obtained via. divided differences.
% 
% Input:
%   P - The polynomial coefficients, generated by divdif
%   t_int - The interpolating points used for P
%   t_test - The sample points to be evaluated
% 
% Output:
%   pt - the interpolant evaluated at t_test
%

%Compute the polynomial for all test points at once
n = length(P)-1; %coefficients c_0, ... c_n
Np = length(t_test);
pt(1:Np,1) = P(n+1);

for j=n-1:-1:0
    pt = (t_test-t_int(j+1)).*pt + P(j+1);
end